dados='dados/brasil_estados.parquet'
mapa='dados/brazil-states.geojson.txt'
base='dados/ecommerce.parquet'
world='dados/countries.geojson'
descritivas=[
    'Estado',
    'Região',
    'Sigla'
]
continuas=[
    'População',
    'Densidade Demográfica',
    'Veículos',
    'IDEB EF',
    'IDEB EM',
    'Rendimento per Capita',
    'Ocupação ',
    'Rendimento Ocupação',
    'IDH',
    'Área',
    'Área Urbana'
]
