dados='dados/brasil_estados.parquet'
mapa='dados/brazil-states.geojson.txt'
descritivas=[
    'Estado',
    'Região'
]
continuas=[
    'População',
    'Densidade Demográfica',
    'Veículos',
    'IDEB EF',
    'IDEB EM',
    'Rendimento per Capita',
    'Ocupação ',
    'Rendimento Ocupação',
    'IDH',
    'Área',
    'Área Urbana'
]
